version: 0.2

phases:
  install:
    commands:
      - echo Initializing docker daemon...
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - pip install -r src/requirements.txt
      - echo The following is only required if we use DLC images as our base 'FROM' images.
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 763104351884.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building $FRAMEWORK framework...
      - python src/main.py --buildspec $FRAMEWORK/buildspec.yml --framework $FRAMEWORK
  post_build:
    commands:
      - echo Build step finished on `date`
artifacts:
  files:
    - $BUILD_RESULTS_PATH
  name: BUILD_RESULTS
  discard-paths: yes