blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://repost.aws/tags/TAhMWeHkpfSMSCxIFNqcqYog/amazon-braket
    about: Use AWS Developer Forums to ask and answer questions
