account_id: &ACCOUNT_ID <set-$ACCOUNT_ID-in-environment>
region: &REGION <set-$REGION-in-environment>
framework: &FRAMEWORK tensorflow
version: &VERSION 2.4.1
short_version: &SHORT_VERSION 2.4

repository_info:
  jobs_repository: &JOBS_REPOSITORY
    image_type: &JOBS_IMAGE_TYPE jobs
    root: !join [ *FRAMEWORK, "/", *JOBS_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *JOBS_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]

context:
  jobs_context: &JOBS_CONTEXT
    entrypoint:
      source: docker/artifacts/dockerd-entrypoint.py
      target: dockerd-entrypoint.py
    braket_container:
      source: ../../src/braket_container.py
      target: braket_container.py

images:
  BuildTensorflowCPUJobsPy3DockerImage:
    <<: *JOBS_REPOSITORY
    build: &TENSORFLOW_CPU_JOBS_PY3 false
    image_size_baseline: 7026
    device_type: &DEVICE_TYPE cpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py37
    os_version: &OS_VERSION ubuntu18.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
    context:
      <<: *JOBS_CONTEXT
